    title1 = "<b># Ode to Alvin: The Web Weaver </b>"
    let word1 = "<b> realm </b>"
    let word2 = "<b> pixels </b>"
    let word3 = "<b> code </b>"
    let word4 = "<b><i> **web weaver** </i></b>"
    let word4$ = "<b> pearls. </b>"
    title2 = "<b>## I. The Blank Canvas </b>"
    let name = "<b> Alvin </b>"
    let word5 = "<b><i> **alchemist of the browser**, </i></b>"
    let word6 = "<b> keyboard </b>"
    let word7 = "<b> wand, </b>"
    let word8 = "<b> pages </b>"
    let word9 = "<b> Painting </b>"

    title3 = "<b>## II. The HTML Symphony</b>"
    let word10 = "<b> fingers </b>"
    let word11 = "<b> keys, </b>"
    let word12 = "<b> tags </b>"
    let word13 = "<b> HTML </b>"
    let word14 = "<b> symphonies </b>"

    title4 = "<b>## III. The CSS Enchanter</b>"
    let word15 = "<b><i> **CSS cloak**, </i></b>"
    let word16 = "<b> Styling </b>"
    let word17 = "<b> Colors bloom, fonts sing, </b>"
    let word18 = " evoke, </b>"
    let word19 = " visual </b>"

    title5 = "<b>## IV. The JavaScript Magician</b>"
    let word20 = "<b> magic </b>"
    let word21 = "<b><i> **JavaScript spells**, </i></b>"
    let word22 = "<b> will, </b>"
    let word23 = "<b> Forms </b>"
    let word24 = "<b> animation propel. </b>"

    title6 = "<b>## V. The Debugging Sage</b>"
    let word25 = "<b> bugs </b>"
    let word26 = "<b><i> **debugging spectacles**, </i></b>"
    let word27 = "<b> glitches </b>"
    let word27$ = "<b> code's arc, </b>"
    let word28 = "<b> tames </b>"
    let word29 = "<b> variables. </b>"

    title7 = "<b>## VI. The Responsive Voyager</b>"
    let word30 = "<b> Across </b>"
    let word31 = "<b> devices, </b>"
    let word32 = "<b><i> *responsive sea**, </i></b>"
    let word33 = "<b> guide </b>"
    let word34 = "<b> Adapting </b>"
    let word35 = "<b> fluidity. </b>"

    title8 = "<b>## VII. The The SEO Whisper</b>"
    let word36 = "<b> labyrinth </b>"
    let word37 = "<b><i> **SEO whisperer**, </i></b>"
    let word38 = "<b> Meta tags, </b>"
    let word39 = "<b> wanderers. </b>"

    title9 = "<b>## VIII. The Git Alchemist</b>"
    let word40 = "<b> mystical potion, </b>"
    let word41 = "<b> Git's </b>"
    let word42 = "<b> merge </b>"
    let word43 = "<b> repository </b>"
    let word44 = "<b> code </b>"

    title10 = "<b>## IX. The Deployment Dreamer</b>"
    let word45 = "<b> moon </b>"
    let word46 = "<b> world, </b>"
    let word47 = "<b> Deployments </b>"
    let word48 = "<b> website </b>"
    let word49 = "<b> unfurled.</b>"

    title11 = "<b>## X. The The Web Developer's Anthem</b>"
    let word50 = "<b><i> **web developer**, </i></b>"
    let word51 = "<b> pixels, </b>"
    let word52 = "<b> clicks, </b>"
    let word53 = "<b> binary </b>"
    let word54 = "<b> matrix.</b>"
    let word55 = "<i>*Rod, may your lines be bug-free,<br>And may your JavaScript forever flow,<br>As you navigate the web's eternal ebb and flow.*</i>"
    
    function myfunction1() { 
        document.getElementById("demo").innerHTML= title1 + "<br><br>" + 'In the' + word1 + "of ones and zeros" + "<br>" + "Where" + word2 + "dance and" + word3 + "unfurls," + "<br>" + "These resides a silent sorcerer," + "<br>" + "A" + word4 + "with dreams and" + word4$ + "<br><br>" + title2 + "<br><br>" + name + ", the" + word5 + "<br>" + "Wields his" + word6 + "like a" + word7 + "<br>" + "He conjures" + word8 + "from thin air," + "<br>" + word9 + "landscapes with lines so fond." + "<br><br>" + title3 + "<br><br>" + "His" + word10 + "dance upon the" + word11 + "<br>" + "Crafting" + word12 + "like musical notes," + "<br>" + word13 + "whispers secretes to the breeze," + "<br>" + "As" + name + "orchestrates" + word14 + "in quotes." + "<br><br>" + title4 + "<br><br>" + "Next, he dons his" + word15 + "<br>" + word16 + "elements with flair and grace," + "<br>" + word17 + "layouts" + word18 + "<br>" + "A" + word19 + "ballet in this digital space." + "<br><br>" + title5 +  "<br><br>" + "But wait, the" + word20 + "deepens still," + "<br>" + name + "summons" + word21 + "<br>" + "Interactivity blooms at his" + word22 + "<br>" + word23 + "validate," + word24 + "<br><br>" + title6 + "<br><br>" + "Yet," + word25 + "creep in like shadows dark," + "<br>" + name + "dons his" + word26 + "<br>" + "Chasing" + word27 + "through the" + word27$ + "<br>" + "He" + word28 + "wild loops and elusive" + word29 + "<br><br>" + title7 + "<br><br>" + word30 + "screens," + word31 + "and dimensions," + "<br>" + name + "sails on the" + word32 + "<br>" + "Media queries" + word33 + "his intentions," + "<br>" + word34 + "layouts with" + word35 + "<br><br>" + title8 + "<br><br>" + "In the" + word36 + "of search engines," + "<br>" + name + "becomes an" + word37 + "<br>" + "keywords, backlink strings," + "<br>" + "He crafts pathways to digital" + word38 + "<br><br>" + title9 + "<br><br>" + "Version control, a" + word39 + "<br>" + "Version control, a" + word40 + "<br>" + name + "brews commits in" + word41 + "caludron," + "<br>" + "Branches fork," + word42 + "conflicts in motion," + "<br>" + "His" + word43 + "a saga of" + word44 + "reborn." + "<br><br>" + title10 + "<br><br>" + "And when the" + word45 + "kisses the horizon," + "<br>" + name + "unfurls his creation to the" + word46 + "<br>" + word47 + "like shooting stars, arisen," + "<br>" + "His" + word48 + "sails, its sails" + word49 + "<br><br>" + title11 + "<br><br>" + "So here's to" + name + ", the" + word50 + "<br>" + "A poet of" + word51 + "a composer of" + word52 + "<br>" + "In the" + word53 + "sumphony, he's the reveler," + "<br>" + "Waving dreams into the digital" + word54 + "<br><br><br>" + word55;
    }

